name: Log latest release

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:

      - id: terragrunt
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gruntwork-io/terragrunt

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tap: evanstoddard23/tap
          formula: terragrunt
          tag: ${{ steps.terragrunt.outputs.release }}
