name: update-formula

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-terragrunt:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Find Latest Version
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gruntwork-io/terragrunt
          excludes: prerelease, draft

      - name: Check Version Status
        run: echo "::set-env name=VERSION_STATUS::$(grep ${{ steps.latest.outputs.release }} terragrunt.rb >/dev/null; echo $?)"
        working-directory: Formula

      - name: Update Homebrew formula
        if: env.VERSION_STATUS == 1
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          tap: evanstoddard23/tap
          formula: terragrunt
          force: true
          token: ${{ secrets.PAT }}
          tag: ${{ steps.latest.outputs.release }}

  update-tfsec:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Find Latest Version
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: liamg/tfsec
          excludes: prerelease, draft

      - name: Check Version Status
        run: echo "::set-env name=VERSION_STATUS::$(grep ${{ steps.latest.outputs.release }} tfsec.rb >/dev/null; echo $?)"
        working-directory: Formula

      - name: Update Homebrew formula
        if: env.VERSION_STATUS == 1
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          tap: evanstoddard23/tap
          formula: tfsec
          force: true
          token: ${{ secrets.PAT }}
          tag: ${{ steps.latest.outputs.release }}
