name: update-terragrunt

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/2 * * * *'

jobs:
  update-terragrunt:
    runs-on: ubuntu-latest
    steps:

      - name: Find Latest Terragrunt Version
        id: terragrunt-latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gruntwork-io/terragrunt

      - name: Check Version Status
        run: echo "::set-env name=VERSION_STATUS::$(grep ${{ steps.terragrunt-latest.outputs.release }} terragrunt.rb >/dev/null; echo $?)"
        working-directory: Formula

      - name: Update Homebrew formula
        if: env.VERSION_STATUS == 1
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          tap: evanstoddard23/tap
          formula: terragrunt
          force: true
          token: ${{ secrets.PAT }}
          tag: ${{ steps.terragrunt-latest.outputs.release }}
