name: update-terragrunt

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-terragrunt:
    runs-on: ubuntu-latest
    steps:

      - name: Find Latest Terragrunt Version
        id: terragrunt-latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: gruntwork-io/terragrunt

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          tap: evanstoddard23/tap
          formula: terragrunt
          force: true
          token: ${{ secrets.PAT }}
          tag: ${{ steps.terragrunt-latest.outputs.release }}
